### ISSUE TITLE
Pawns pick up and drop things infinitely

### ISSUE THREAD

**Issue by bziur** [Mehni/PickUpAndHaul#1]
Sometimes a pawn can be found picking up and droping a stack of something in a loop.

In my case it was a stack of beer. The person was carying some items, and there were spots to place the items, still, the pawn would pick up an item and drop it. next to himself.
Drafting doesnt seem to help, disabling hauling for the affected pawn causes another pawn to get into the loop.
The pawn was in a corner of a room, I have no idea if that matters though.

I'm using While Youre Up mod too, although according to steam comments people seem to get the issue without mods that could affect the hauling.

**Comment by Mehni** [comment]
Lemme know if the new v0.18.1.0 release fixes this issue for you.
