### ISSUE TITLE
Pawn infinitely tries to pick and store several items, with only 1 available spot.

### ISSUE THREAD

**Issue by Valerate** [Mehni/PickUpAndHaul#14]
Hi

Today I had an issue with the pawn who was trying to pick-up-and-haul several items at the same time (which is the purpose of the pick-up-and-haul mod) but the problem was that there only one available spot in the stockpile and the pawn tried to pick up 3+ items. I assume it failed and kept trying over and over until I filled that one spot / removed the items. At which point the error spam went away and the game continued

Here's the log entries: 

https://gist.github.com/HugsLibRecordKeeper/2f12150db739abff2578f905272e2271#file-output_log-txt-L1883

**Comment by Mehni** [comment]
Does the issue persist with the latest GitHub (2018/11/01) or Steam release?
