### ISSUE TITLE
[BUG] Cause like infinite loops with Miscellaneous.MAI

### ISSUE THREAD

**Issue by lin1987www** [Mehni/PickUpAndHaul#25]
When MAI go out world's map then come back settlement, it seems like MAI push jobs in queue while MAI is in world's map.

[Miscellaneous.MAI](https://github.com/HaploX1/RimWorld-Miscellaneous_Mods/tree/master/Mods/Miscellaneous_MAI)
https://github.com/HaploX1/RimWorld-Miscellaneous_Mods/tree/master/Mods/Miscellaneous_MAI

-----------------
And another bug is NullReferenceException

Exception filling tab RimWorld.ITab_Pawn_Gear: System.NullReferenceException: Object reference not set to an instance of an object
at PickUpAndHaul.DrawThingRow_Patch.GetColorForHauled (Verse.Pawn,Verse.Thing) <0x0003f>
at (wrapper dynamic-method) RimWorld.ITab_Pawn_Gear.DrawThingRow_Patch0 (object,single&,single,Verse.Thing,bool) <0x00413>
at RimWorld.ITab_Pawn_Gear.FillTab () <0x00a65>
at Verse.InspectTabBase/<DoTabGUI>c__AnonStorey0.<>m__0 () <0x00118>

Verse.Log:Error(String, Boolean)
Verse.Log:ErrorOnce(String, Int32, Boolean)
Verse.<DoTabGUI>c__AnonStorey0:<>m__0()
Verse.ImmediateWindow:DoWindowContents(Rect)
Verse.<WindowOnGUI>c__AnonStorey0:<>m__0(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)

Mouse position stack is not empty. There were more calls to BeginScrollView than EndScrollView. Fixing.
Verse.Log:Error(String, Boolean)
Verse.Widgets:EnsureMousePositionStackEmpty()
Verse.Root:Update_Patch1(Object)
Verse.Root_Play:Update()

**Comment by Mehni** [comment]
Release is outdated, build from master or use dll from Assemblies folder. That fixes NRE. New release will follow after testing new Deep Storage compatibility. ETA of one week.

Not looked into other issue yet. Do you have repro steps? How do I trigger the bug?

**Comment by lin1987www** [comment]
I notice it will happen at MAI want to rest and want to haul some cause like infinite loops, if I draft she to move her bed closely, then toggle draft she will go sleep.

This is sound weird, it seems like MAI have two job queue?
