### ISSUE TITLE
Compatibility issue with Allow Tool's haul urgently and corpses.

### ISSUE THREAD

**Issue by Dyrewulfe** [Mehni/PickUpAndHaul#27]
When trying to use PU&H with Allow Tool, I noticed corpses weren't getting hauled urgently. I set up a minimal test environment just be to sure(just hugslib, mod manager, allowtool and pu&h), disabled normal hauling, prioritized haul+, killed a pawn, set the body to be hauled urgently, and dug a grave(and made a dumping stockpile as well). With PU&H active, the body just sits there. Deactivate it, and they haul it off to the grave.

**Comment by Dyrewulfe** [comment]
Hmmm. Not sure why, but a simple delete and reinstall of PU&H resolved this issue.

**Comment by Mehni** [comment]
Alright, thanks for the update
