### ISSUE TITLE
Suggestion: Option to limit queued hauling jobs

### ISSUE THREAD

**Issue by Dyrewulfe** [Mehni/PickUpAndHaul#28]
Hello again. I was thinking it might be nice to have an option exposed to limit the number of hauling jobs a pawn can queue up. I've noticed that occasionally pawns will grab so much stuff(especially bionic pawns), that they can end up unloading their inventory until well past their bedtimes.

**Comment by Mehni** [comment]
I won't add settings to PU&H. It's complex enough as is
