### ISSUE TITLE
Colonists won't haul

### ISSUE THREAD

**Issue by Rodalorn** [Mehni/PickUpAndHaul#31]
I have Rimworld 1.1.2552 (64 bit). 

Installed Mods: 
Core
Pick up and Haul 1.1

With pick up and haul enabled, pawns will not haul when assigned to haul.

**Comment by Mehni** [comment]
Do you have a log? It's in your appdata folder. Or use Hugslib to generate one.

**Comment by Rodalorn** [comment]
Thank you for the reply.  I was able to get it working, I may have
downloaded the wrong file.  I couldn't figure out how to remove my post.
