### ISSUE TITLE
[1.1] Mod erases large hauled stacks

### ISSUE THREAD

**Issue by Tharn** [Mehni/PickUpAndHaul#33]
`Invalid count: -861, setting to 1. Job was HaulToInventory (Job_30088386) A=Thing_Meat_Ibex10399588 B=(120, 0, 122)`

This is in conjunction with StackXXL.

The pawn was trying to haul, I believe, several hundred units at the time.

**Comment by magneticflux-** [comment]
Since it went negative, it seems like integer overflow. Just how big of a stack are we talking? >=64k stacks? I don't think anything would store a Byte value since Vanilla stacks can go over 256, and a Short is the next biggest.

**Comment by Tharn** [comment]
No, I think it was a 650ish stack. That's the max for me.
