### ISSUE TITLE
Misc Robots ++ hauling issues

### ISSUE THREAD

**Issue by BryanAldrich** [Mehni/PickUpAndHaul#34]
I did some debugging, the general error you get is this:

`JobDriver threw exception in initAction for pawn OmniBot 35 driver=JobDriver_HaulToInventory (toilIndex=2) driver.job=(HaulToInventory (Job_10302090) A=Thing_ComponentSpacer2632801 B=(155, 0, 142))
System.NullReferenceException: Object reference not set to an instance of an object
  at PickUpAndHaul.JobDriver_HaulToInventory+<>c__DisplayClass1_0.<MakeNewToils>b__2 () [0x000db] in <956c8985da554f8d8240abfc20c81364>:0 
  at Verse.AI.JobDriver.TryActuallyStartNextToil () [0x001df] in <4489f1367c1c4d76b2ae1272c8ed691d>:0 
Verse.Log:Error(String, Boolean)
Verse.AI.JobUtility:TryStartErrorRecoverJob(Pawn, String, Exception, JobDriver)
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()`

The issue is the robots don't have a CompHauledToInventory Comp. I don't know how to handle this else I'd submit a pull request with a proper fix.

**Comment by Mehni** [comment]
Discussed on the RW discord. Common Sense adds/changes OpportunisticTasks which doesn't respect the workgiver in PU&H. 

I fear this is not something I can fix on my end. Even if I'd change the jobdriver to GTFO if there's no comp, Common Sense would still assign the HaulToInventoryJob. That'd result in a loop until RimWorld notices the pawn starting 10 jobs in 10 ticks and resets their job.  Which is a worse result, as it's quite disruptive.

There might be side effects to giving bots a CompHauledToInventory Comp. Worst case scenarios include making them unload until they fully discharge, or they despawn when they return to their charging station (including despawning their inventory). It's worth a shot/experiment. Or just disable the Opportunistic Hauling option in question ;)

https://gist.github.com/HugsLibRecordKeeper/b6211aa035f03fe261bd78f58f71fd66
