### ISSUE TITLE
Suggestion/Issue: Mod Settings Menu for compatibility with High Carrying Capacity modded pawns.

### ISSUE THREAD

**Issue by Nutarama** [Mehni/PickUpAndHaul#35]
### Background

Pick Up and Haul by default tries to fill a pawn's entire inventory when assigned a hauling job.  This can mean using the pathing algorithm to go to several stacks to pick them up.  This is a minor TPS hit for vanilla pawns when the algorithm has to do the pathing, but given that vanilla pawns have a low carrying capacity the typical number of stacks to path to is low.  However, when playing with multiple mods that increase Carrying Capacity in multiple ways, like a combinations of hediffs, apparel, and character-specific stats, Carrying Capacity can go from 35 to several hundred if not even into the thousands.

### The Issue

When a pawn has say 700 Carrying Capacity (20 times vanilla and reasonable for some modded pawns), the pawn given a hauling job will still try to fill their entire inventory.  If I mark all Steel Slag chunks for hauling and tell a pawn to prioritize hauling one, this means that instead of pathing to the nearest 7 Steel Slag Chunks to add to the inventory (since Steel Slag Chunks weigh 5 kg), the pawn will try to path to 140 Steel Slag Chunks.

This involves a significant hit to TPS on the ticks when the job is assigned as the pathing algorithm cannot efficiently create a path to all the nodes in the time given for a single tick while maintaining capped TPS.  This also means that the job can create very long paths which can force a pawn to be adding things to their inventory for several in-game hours and ignore the pawn's other needs, especially if the hauling job is prioritized as explained above.

### One Solution

Add a Mod Settings menu to the mod with two options: one, a checkbox to limit the number of nodes designated for the pathing algorithm per hauling job - this would by default be unchecked and thus the mod would maintain current behavior.  Checking the box would limit the number of nodes as defined by the second option, a numerical slider that goes from 1 to an upper bound (20? 50?  Some decently large number that doesn't make the slider hard to use.)

By setting the slider and checking the checkbox, the mod upon generating a hauling job would limit the number of additional stacks to add to the pawn's inventory to the number selected on the slider.  If it's 1, only one additional stack would be added to the inventory for future unloading.  This would make the pathing have a smaller TPS impact (as it only queues one additional node to move to) and it would shorten the duration of the hauling job for the above mentioned modded pawns to avoid very long-duration hauling jobs.

As it would be user-configurable through mod settings and not an XML and disabled by default, this would allow players on heavily modded playthroughs additional functionality while preserving the Ease of Use factor of the mod.  Experienced players would be able to easily change the vlaue for performance without an XML patch, and inexperienced or uncaring players could simply ignore the setting and use current behavior.

### Downsides

Writing a Mod Settings menu would require the use of custom C# code to make the menu work.

**Comment by Mehni** [comment]
Hi. Thanks for the well-reasoned suggestion.

The answer is no. You decided to follow the good ol' "Mod it till it breaks" motto, so don't be surprised when it breaks.

> When a pawn has say 700 Carrying Capacity (20 times vanilla and reasonable for some modded pawns),

I don't find this reasonable. This also doesn't seem common, so I shan't add support for it.
