### ISSUE TITLE
Incompatibility issue with Flickable Storage mod

### ISSUE THREAD

**Issue by AlisonHuang777** [Mehni/PickUpAndHaul#56]
https://github.com/user-attachments/assets/383b46b4-4286-499a-b5cf-d1927a5b9a73

Log: https://gist.github.com/HugsLibRecordKeeper/d87aca6a3d8043151a091e1d66a66375

**Comment by Mehni** [comment]
Pick Up and Haul uses `StoreUtility.TryFindBestBetterStorageFor` to determine where to haul items to. Flickable Storage patches a bunch of methods in StoreUtility to make their mod work, but doesn't patch TryFindBestBetterStorageFor.

Not an issue in PUAH.

**Comment by emipa606** [comment]
The only method patched is the IHaulDestination.Accepts. Ill take a look if the StoreUtility.TryFindBestBetterStorageFor somehow skips the check if an item is allowed.

**Comment by emipa606** [comment]
Yes, that method uses another check since 1.5. Was causing different issues in vanilla so nothing to do with PUAH. Fixed now, thanks for the input Mehni!
