### ISSUE TITLE
Pickup and Haul Error when viewing colonist as he queues jobs

### ISSUE THREAD

**Issue by Amnesiac9** [Mehni/PickUpAndHaul#9]
This happens every once in a while:
Screenshot: https://i.imgur.com/RoemHk0.png
Log: https://git.io/fAMkd

It happens while I have a colonist selected and they queue a job, only sometimes though. Not always. It's hard to "make" it happen, but it just happened when I selected a pawn and told him to prioritize hauling some rice. He collected a few other rices around, then as soon as the rice appeared in his hands, the error log got spammed by that.

Hope someone can figure out what this is!

**Comment by Mehni** [comment]
DrawLinesBetweenTargets() draws a line between the targetA for each queued job. Pick Up and Haul doesn't set the targetA until the unload job starts, so it's a null target. Part of that was alleviated in commit 4e3c8ae931a58e84db1d276889ad5eaece9136cc by setting the executing pawn as targetA, but in certain instances that isn't sufficient.
